version: "3.3"
services:
  groceries-frontend-dev:
    build:
      context: ./frontend/
      dockerfile: dev.Dockerfile
    image: groceries-frontend-dev
    container_name: groceries-frontend-dev
    volumes:
      - /home/mat/docker/groceries-app/frontend/src:/app/src
      - /home/mat/docker/groceries-app/frontend/public:/app/public
      - /home/mat/docker/groceries-app/frontend/rollup.config.js:/app/rollup.config.js
  groceries-backend-dev:
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    image: groceries-backend-dev
    container_name: groceries-backend-dev
    volumes:
      - /home/mat/docker/groceries-app/backend/db_dev.json:/app/db.json
      - /home/mat/docker/groceries-app/backend/main.py:/app/main.py
networks:
  default:
    external: true
    name: proxy
