version: "3.3"
services:
  groceries-frontend-dev:
    build:
      context: ./frontend/
      dockerfile: dev.Dockerfile
    image: groceries-frontend-dev
    container_name: groceries-frontend-dev
    ports:
      - 6000:6000
    volumes:
      - ./frontend/src:/app/src:z
      - ./frontend/public:/app/public:z
      - ./frontend/rollup.config.js:/app/rollup.config.js:z
  groceries-backend-dev:
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    image: groceries-backend-dev
    container_name: groceries-backend-dev
    ports:
      - 6001:6001
    volumes:
      - ./backend/db_dev.json:/app/db.json:z
      - ./backend/main.py:/app/main.py:z