services:
  groceries:
    image: ghcr.io/mathieumoalic/groceries-app:3.1.1
    container_name: groceries
    environment:
      - MEILI_URL=${MEILI_URL}
      - MEILI_KEY=${MEILI_KEY}
    ports:
      - 6001:6001
    volumes:
      - ./data:/data:z

  groceries-meilisearch:
    image: docker.io/getmeili/meilisearch:v1.2.0
    container_name: groceries-meilisearch
    environment:
      - MEILI_MASTER_KEY=${MEILI_KEY}
      - MEILI_ENV=production
      - MEILI_NO_ANALYTICS
    ports:
      - 6002:7700
    volumes:
      - ./meili_data:/meili_data:z